<?php
			if( function_exists('acf_add_local_field_group') ):

                acf_add_local_field_group(array(
                    'key' => 'group_618fc7fde5020',
                    'title' => 'Recipe Details',
                    'fields' => array(
                        array(
                            'key' => 'field_61ad6327afd56',
                            'label' => 'Palavra-chave',
                            'name' => 'recipepress_keywords',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => 'Na dúvida coloque o nome da receita sem "receita" ou "recipe" no começo.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61cb62a084d57',
                            'label' => 'Introdução da Receita',
                            'name' => 'recipepress_recipe_description',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                        array(
                            'key' => 'field_61c7acb947d2e',
                            'label' => 'Recipe Cuisine',
                            'name' => 'recipepress_recipe_cuisine',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => 'recipepress_recipe_cuisine',
                            ),
                            'taxonomy' => 'recipepress_recipecuisine',
                            'field_type' => 'checkbox',
                            'add_term' => 1,
                            'save_terms' => 1,
                            'load_terms' => 1,
                            'return_format' => 'id',
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                        array(
                            'key' => 'field_61c7ad0747d30',
                            'label' => 'Recipe Category',
                            'name' => 'recipepress_recipe_category',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => 'recipepress_recipe_cuisine',
                            ),
                            'taxonomy' => 'recipepress_recipecategory',
                            'field_type' => 'checkbox',
                            'add_term' => 1,
                            'save_terms' => 1,
                            'load_terms' => 1,
                            'return_format' => 'id',
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                        array(
                            'key' => 'field_618fc9f7af845',
                            'label' => 'Rendimento da receita (Quantas Porções rendem)',
                            'name' => 'recipepress_recipeYield',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ad674f0e1ef',
                            'label' => 'Tempo de Preparo',
                            'name' => 'recipepress_prepTime',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '34',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'PT5M' => '5 Minutes',
                                'PT10M' => '10 Minutes',
                                'PT15M' => '15 Minutes',
                                'PT20M' => '20 Minutes',
                                'PT25M' => '25 Minutes',
                                'PT30M' => '30 Minutes',
                                'PT35M' => '35 Minutes',
                                'PT40M' => '40 Minutes',
                                'PT45M' => '45 Minutes',
                                'PT50M' => '50 Minutes',
                                'PT55M' => '55 Minutes',
                                'PT60M' => '60 Minutes',
                                'PT65M' => '65 Minutes',
                                'PT70M' => '70 Minutes',
                                'PT75M' => '75 Minutes',
                                'PT80M' => '80 Minutes',
                                'PT85M' => '85 Minutes',
                                'PT90M' => '90 Minutes',
                                'PT95M' => '95 Minutes',
                                'PT100M' => '100 Minutes',
                                'PT105M' => '105 Minutes',
                                'PT110M' => '110 Minutes',
                                'PT115M' => '115 Minutes',
                                'PT120M' => '120 Minutes',
                                'PT125M' => '125 Minutes',
                                'PT130M' => '130 Minutes',
                                'PT135M' => '135 Minutes',
                                'PT140M' => '140 Minutes',
                                'PT145M' => '145 Minutes',
                                'PT150M' => '150 Minutes',
                                'PT155M' => '155 Minutes',
                                'PT160M' => '160 Minutes',
                                'PT165M' => '165 Minutes',
                                'PT170M' => '170 Minutes',
                                'PT175M' => '175 Minutes',
                                'PT180M' => '180 Minutes',
                                'PT185M' => '185 Minutes',
                                'PT190M' => '190 Minutes',
                                'PT195M' => '195 Minutes',
                                'PT200M' => '200 Minutes',
                                'PT205M' => '205 Minutes',
                                'PT210M' => '210 Minutes',
                                'PT215M' => '215 Minutes',
                                'PT220M' => '220 Minutes',
                                'PT225M' => '225 Minutes',
                                'PT230M' => '230 Minutes',
                                'PT235M' => '235 Minutes',
                                'PT240M' => '240 Minutes',
                                'PT245M' => '245 Minutes',
                                'PT250M' => '250 Minutes',
                                'PT255M' => '255 Minutes',
                                'PT260M' => '260 Minutes',
                                'PT265M' => '265 Minutes',
                                'PT270M' => '270 Minutes',
                                'PT275M' => '275 Minutes',
                                'PT280M' => '280 Minutes',
                                'PT285M' => '285 Minutes',
                                'PT290M' => '290 Minutes',
                                'PT295M' => '295 Minutes',
                                'PT300M' => '300 Minutes',
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_61ad672c0e1ee',
                            'label' => 'Tempo de Cozimento',
                            'name' => 'recipepress_cookTime',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '33',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'PT0M' => 'cooking not necessary',
                                'PT5M' => '5 Minutes',
                                'PT10M' => '10 Minutes',
                                'PT15M' => '15 Minutes',
                                'PT20M' => '20 Minutes',
                                'PT25M' => '25 Minutes',
                                'PT30M' => '30 Minutes',
                                'PT35M' => '35 Minutes',
                                'PT40M' => '40 Minutes',
                                'PT45M' => '45 Minutes',
                                'PT50M' => '50 Minutes',
                                'PT55M' => '55 Minutes',
                                'PT60M' => '60 Minutes',
                                'PT65M' => '65 Minutes',
                                'PT70M' => '70 Minutes',
                                'PT75M' => '75 Minutes',
                                'PT80M' => '80 Minutes',
                                'PT85M' => '85 Minutes',
                                'PT90M' => '90 Minutes',
                                'PT95M' => '95 Minutes',
                                'PT100M' => '100 Minutes',
                                'PT105M' => '105 Minutes',
                                'PT110M' => '110 Minutes',
                                'PT115M' => '115 Minutes',
                                'PT120M' => '120 Minutes',
                                'PT125M' => '125 Minutes',
                                'PT130M' => '130 Minutes',
                                'PT135M' => '135 Minutes',
                                'PT140M' => '140 Minutes',
                                'PT145M' => '145 Minutes',
                                'PT150M' => '150 Minutes',
                                'PT155M' => '155 Minutes',
                                'PT160M' => '160 Minutes',
                                'PT165M' => '165 Minutes',
                                'PT170M' => '170 Minutes',
                                'PT175M' => '175 Minutes',
                                'PT180M' => '180 Minutes',
                                'PT185M' => '185 Minutes',
                                'PT190M' => '190 Minutes',
                                'PT195M' => '195 Minutes',
                                'PT200M' => '200 Minutes',
                                'PT205M' => '205 Minutes',
                                'PT210M' => '210 Minutes',
                                'PT215M' => '215 Minutes',
                                'PT220M' => '220 Minutes',
                                'PT225M' => '225 Minutes',
                                'PT230M' => '230 Minutes',
                                'PT235M' => '235 Minutes',
                                'PT240M' => '240 Minutes',
                                'PT245M' => '245 Minutes',
                                'PT250M' => '250 Minutes',
                                'PT255M' => '255 Minutes',
                                'PT260M' => '260 Minutes',
                                'PT265M' => '265 Minutes',
                                'PT270M' => '270 Minutes',
                                'PT275M' => '275 Minutes',
                                'PT280M' => '280 Minutes',
                                'PT285M' => '285 Minutes',
                                'PT290M' => '290 Minutes',
                                'PT295M' => '295 Minutes',
                                'PT300M' => '300 Minutes',
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_61ad67710e1f0',
                            'label' => 'Tempo Total',
                            'name' => 'recipepress_totalTime',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '33',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'PT5M' => '5 Minutes',
                                'PT10M' => '10 Minutes',
                                'PT15M' => '15 Minutes',
                                'PT20M' => '20 Minutes',
                                'PT25M' => '25 Minutes',
                                'PT30M' => '30 Minutes',
                                'PT35M' => '35 Minutes',
                                'PT40M' => '40 Minutes',
                                'PT45M' => '45 Minutes',
                                'PT50M' => '50 Minutes',
                                'PT55M' => '55 Minutes',
                                'PT60M' => '60 Minutes',
                                'PT65M' => '65 Minutes',
                                'PT70M' => '70 Minutes',
                                'PT75M' => '75 Minutes',
                                'PT80M' => '80 Minutes',
                                'PT85M' => '85 Minutes',
                                'PT90M' => '90 Minutes',
                                'PT95M' => '95 Minutes',
                                'PT100M' => '100 Minutes',
                                'PT105M' => '105 Minutes',
                                'PT110M' => '110 Minutes',
                                'PT115M' => '115 Minutes',
                                'PT120M' => '120 Minutes',
                                'PT125M' => '125 Minutes',
                                'PT130M' => '130 Minutes',
                                'PT135M' => '135 Minutes',
                                'PT140M' => '140 Minutes',
                                'PT145M' => '145 Minutes',
                                'PT150M' => '150 Minutes',
                                'PT155M' => '155 Minutes',
                                'PT160M' => '160 Minutes',
                                'PT165M' => '165 Minutes',
                                'PT170M' => '170 Minutes',
                                'PT175M' => '175 Minutes',
                                'PT180M' => '180 Minutes',
                                'PT185M' => '185 Minutes',
                                'PT190M' => '190 Minutes',
                                'PT195M' => '195 Minutes',
                                'PT200M' => '200 Minutes',
                                'PT205M' => '205 Minutes',
                                'PT210M' => '210 Minutes',
                                'PT215M' => '215 Minutes',
                                'PT220M' => '220 Minutes',
                                'PT225M' => '225 Minutes',
                                'PT230M' => '230 Minutes',
                                'PT235M' => '235 Minutes',
                                'PT240M' => '240 Minutes',
                                'PT245M' => '245 Minutes',
                                'PT250M' => '250 Minutes',
                                'PT255M' => '255 Minutes',
                                'PT260M' => '260 Minutes',
                                'PT265M' => '265 Minutes',
                                'PT270M' => '270 Minutes',
                                'PT275M' => '275 Minutes',
                                'PT280M' => '280 Minutes',
                                'PT285M' => '285 Minutes',
                                'PT290M' => '290 Minutes',
                                'PT295M' => '295 Minutes',
                                'PT300M' => '300 Minutes',
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_61d048c401b56',
                            'label' => 'Conclusão',
                            'name' => 'recipepress_recipe_conclusion',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'recipe',
                            ),
                        ),
                    ),
                    'menu_order' => 1,
                    'position' => 'acf_after_title',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 1,
                ));
                
                acf_add_local_field_group(array(
                    'key' => 'group_61c7a5d751691',
                    'title' => 'Recipe Ingredients',
                    'fields' => array(
                        array(
                            'key' => 'field_618fc805af841',
                            'label' => 'Recipe Ingredients Text (Utilizado para View)',
                            'name' => 'recipepress_recipe_ingredients_text',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                        array(
                            'key' => 'field_61b677dbefc62',
                            'label' => 'Recipe Ingredients List (Utilizado para Schema)',
                            'name' => 'recipepress_recipe_ingredients_list',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => 'Adicionar Linha',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_61b67833efc64',
                                    'label' => 'Ingredient',
                                    'name' => 'recipepress_recipe_instructions_list_item',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'Recipe Item',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'parent_repeater' => 'field_61b677dbefc62',
                                ),
                            ),
                            'rows_per_page' => 20,
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'recipe',
                            ),
                        ),
                    ),
                    'menu_order' => 10,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 1,
                ));
                
                acf_add_local_field_group(array(
                    'key' => 'group_61c7a5cfea3ed',
                    'title' => 'Recipe Step by Step',
                    'fields' => array(
                        array(
                            'key' => 'field_618fc86caf842',
                            'label' => 'Recipe Instructions Text (Utilizado para View)',
                            'name' => 'recipepress_recipe_instructions_text',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                        array(
                            'key' => 'field_61b6780befc63',
                            'label' => 'Recipe Instructions List (Utilizado para Schema)',
                            'name' => 'recipepress_recipe_instructions_list',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => 'field_61b6785cefc65',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => 'Add Step',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_61b6785cefc65',
                                    'label' => 'step by step',
                                    'name' => 'recipepress_recipe_instructions_list_item',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'parent_repeater' => 'field_61b6780befc63',
                                ),
                            ),
                            'rows_per_page' => 20,
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'recipe',
                            ),
                        ),
                    ),
                    'menu_order' => 20,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 1,
                ));
                
                acf_add_local_field_group(array(
                    'key' => 'group_61ad87ce9378b',
                    'title' => 'Nutritional Information',
                    'fields' => array(
                        array(
                            'key' => 'field_61ad87d8708bb',
                            'label' => 'Calories',
                            'name' => 'recipepress_nutrition_calories',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'kcal',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ae173ba9d0a',
                            'label' => 'Cholesterol',
                            'name' => 'recipepress_nutrition_cholesterol',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ad891f4a412',
                            'label' => 'Fat',
                            'name' => 'recipepress_nutrition_fat',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ae16f5a9d07',
                            'label' => 'Saturated Fat',
                            'name' => 'recipepress_nutrition_saturated_fat',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ae1760a9d0b',
                            'label' => 'Unsaturated Fat',
                            'name' => 'recipepress_nutrition_unsaturated_fat',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ae1776a9d0c',
                            'label' => 'Trans Fat',
                            'name' => 'recipepress_nutrition_trans_fat',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ad895e4a414',
                            'label' => 'Carbs',
                            'name' => 'recipepress_nutrition_carbs',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ad89344a413',
                            'label' => 'Protein',
                            'name' => 'recipepress_nutrition_protein',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ae183ca2653',
                            'label' => 'Fiber',
                            'name' => 'recipepress_nutrition_fiber',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ae1713a9d08',
                            'label' => 'Sodium',
                            'name' => 'recipepress_nutrition_sodium',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61ae1729a9d09',
                            'label' => 'Sugar',
                            'name' => 'recipepress_nutrition_sugar',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => 'Grams',
                            'maxlength' => '',
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'recipe',
                            ),
                        ),
                    ),
                    'menu_order' => 50,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 1,
                ));
                
                acf_add_local_field_group(array(
                    'key' => 'group_61ad91ead32ad',
                    'title' => 'Video',
                    'fields' => array(
                        array(
                            'key' => 'field_61ad91f2e8e24',
                            'label' => 'Video Name',
                            'name' => 'recipepress_video_name',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_61b1479428c1c',
                            'label' => 'Thumbnail',
                            'name' => 'recipepress_video_thumbnail',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array(
                            'key' => 'field_61b147e228c1d',
                            'label' => 'Description',
                            'name' => 'recipepress_video_description',
                            'aria-label' => '',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '75',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => '',
                        ),
                        array(
                            'key' => 'field_618fc8edaf843',
                            'label' => 'Video URL',
                            'name' => 'recipepress_video_url',
                            'aria-label' => '',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'recipe',
                            ),
                        ),
                    ),
                    'menu_order' => 100,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 1,
                ));
                
                endif;		
                ?>
